// Rotating memory-jogger prompts shown in the Add Contact section of
// Contact Builder, to help someone think of names for their list beyond
// the obvious first few. Purely for display - not stored anywhere.
// Networking and Customer lists get different prompts, since the two
// lists skew toward different kinds of people (see the demographic tip
// on the Contacts page itself).
export const NETWORKING_MEMORY_PROMPTS: string[] = [
  "Who did you eat lunch with in high school?",
  "Who cuts your hair?",
  "Who lives on your street?",
  "Who do you play sports with?",
  "Who did you work with last summer?",
  "Who's your mechanic?",
  "Who sold you your house?",
  "Who was in your wedding?",
  "Who did you buy your vehicle from?",
  "Who's your dentist?",
  "Who do you get coffee with?",
  "Who trained you at your first job?",
  "Who's your kids' teacher or coach?",
  "Who do you carpool with?",
  "Who's your insurance agent?",
  "Who cuts your grass or does your yard work?",
  "Who's your favorite bartender or server?",
  "Who do you see at the dog park?",
  "Who's your realtor?",
  "Who did you go to prom with?",
  "Who do you text on your birthday?",
  "Who's your financial advisor or accountant?",
  "Who do you see every Sunday?",
  "Who was your college roommate?",
  "Who's your go-to babysitter?",
  "Who did you meet on a trip or vacation?",
  "Who's in your group chat?",
  "Who do you see at the gym regularly?",
  "Who was your favorite teacher growing up?",
  "Who do you know from your kids' sports team?",
];

export const CUSTOMER_MEMORY_PROMPTS: string[] = [
  "Who would support you no matter what?",
  "Who bought you a wedding gift?",
  "Who bought you a graduation gift?",
  "Who's really into fitness or working out?",
  "What about your friends' parents?",
  "Who was your old coach?",
  "Who's your pastor or someone from your church?",
  "What about your mom's aunts or grandmas?",
  "Who's willing to spend more for quality over quantity?",
  "Who values organic or natural ingredients?",
  "Who's always trying the latest health trend?",
  "Who spoils their grandkids?",
  "Who's redoing their kitchen or bathroom?",
  "Who takes supplements or vitamins every day?",
  "Who's particular about their skincare routine?",
  "Who hosts the holidays for the whole family?",
  "Who's always the one buying nice gifts for everyone?",
  "Who just became a grandparent?",
  "Who's running a household and doing most of the shopping?",
  "Who's into clean eating or meal prepping?",
  "Who's already loyal to one premium brand for everything they buy?",
  "Who complains about how expensive good products are, but buys them anyway?",
  "Who's the one everyone goes to for advice?",
  "Who just retired or is easing into retirement?",
  "Who's always asking what products or supplements you use?",
];
