// Rotating memory-jogger prompts shown in the Add Contact section of
// Contact Builder, to help someone think of names for their list beyond
// the obvious first few. Purely for display - not stored anywhere.
export const CONTACT_MEMORY_PROMPTS: string[] = [
  "Who did you eat lunch with in high school?",
  "Who cuts your hair?",
  "Who lives on your street?",
  "Who do you play sports with?",
  "Who did you work with last summer?",
  "Who's your mechanic?",
  "Who sold you your house?",
  "Who was in your wedding?",
  "Who did you buy your vehicle from?",
  "Who's your dentist?",
  "Who do you get coffee with?",
  "Who trained you at your first job?",
  "Who's your kids' teacher or coach?",
  "Who do you carpool with?",
  "Who's your insurance agent?",
  "Who cuts your grass or does your yard work?",
  "Who's your favorite bartender or server?",
  "Who do you see at the dog park?",
  "Who's your realtor?",
  "Who did you go to prom with?",
  "Who do you text on your birthday?",
  "Who's your financial advisor or accountant?",
  "Who do you see every Sunday?",
  "Who was your college roommate?",
  "Who's your go-to babysitter?",
  "Who did you meet on a trip or vacation?",
  "Who's in your group chat?",
  "Who do you see at the gym regularly?",
  "Who was your favorite teacher growing up?",
  "Who do you know from your kids' sports team?",
];
