export type Leader = {
  name: string;
  location: string;
  occupations: string;
  themes: string[];
  group: "Angle Team" | "Upline Mentor" | "Cross-Line";
  note?: string;
};

export const LEADERS: Leader[] = [
  // Primary Angle Team leaders
  {
    name: "Alex & Laura Angle",
    location: "Richmond, VA",
    occupations: "Corporate IT sales / Elementary education",
    themes: ["Corporate professionals", "Educators", "Parents", "Building together as a couple"],
    group: "Angle Team",
    note: "Founders of the Angle Team. Alex: William & Mary. Laura: UVA master's. Parents of Adam and Elizabeth.",
  },
  {
    name: "Derrick & Kaprice Tucker",
    location: "Washington DC Metro",
    occupations: "IP Attorney (NASA, 20+ yrs) / Real estate broker (GSA)",
    themes: ["Attorneys", "Government employees", "Highly educated professionals"],
    group: "Angle Team",
    note: "Both attended UMBC. Five children.",
  },
  {
    name: "Kent & Jenna Scheerer",
    location: "Cleveland, OH suburbs",
    occupations: "Corporate sales / Registered Nurse",
    themes: ["Nurses", "Athletes", "Sales professionals", "Entrepreneurship as a family decision"],
    group: "Angle Team",
    note: "Kent played D1-AA football at Duquesne. Four children.",
  },
  {
    name: "Jason & Milynda Abbott",
    location: "Richmond, VA",
    occupations: "Outside sales (construction distribution) / Ophthalmic Technician",
    themes: ["Blue-collar professionals", "Medical field workers", "Working families"],
    group: "Angle Team",
    note: "Jason: Virginia Tech. Three boys.",
  },
  // Upline Diamond mentors
  {
    name: "Mike & Susan Bundy",
    location: "Raleigh, NC",
    occupations: "UPS Driver / Restaurant Owner",
    themes: ["Mentorship", "Consistency", "Simplicity", "Servant leadership"],
    group: "Upline Mentor",
    note: "\"Mike Bundy drove for UPS before building the business full time.\"",
  },
  {
    name: "Larry & Pam Winters",
    location: "Raleigh, NC",
    occupations: "Car Wash Manager / Cashier",
    themes: ["Belief-building", "Encouragement", "Grassroots leadership", "New IBOs"],
    group: "Upline Mentor",
  },
  // Cross-line leaders (other LTD Diamonds, not Angle Team)
  {
    name: "Nathan, Mark & Meredith",
    location: "Woodridge, IL",
    occupations: "Actor / Actress / Massage Therapist",
    themes: ["Family", "Designing life intentionally", "Impact over status"],
    group: "Cross-Line",
  },
  {
    name: "McGrath, Brian & Caryn",
    location: "Mechanicsville, VA",
    occupations: "Bank Manager / Occupational Therapist",
    themes: ["Family freedom", "Responsibility"],
    group: "Cross-Line",
  },
  {
    name: "Markiewicz, Joe & Marybeth",
    location: "Raleigh, NC",
    occupations: "Mechanical Engineer / Banker",
    themes: ["Authenticity", "Credibility", "Freedom"],
    group: "Cross-Line",
  },
  {
    name: "LoBue, Mike & Lauren",
    location: "Bradenton, FL",
    occupations: "Federal Economist / Executive Assistant",
    themes: ["Traditional careers", "Mindset growth", "Ownership"],
    group: "Cross-Line",
  },
  {
    name: "Leininger, Alan & Michele",
    location: "Odessa, FL",
    occupations: "Electrical Engineer / Computer Engineer",
    themes: ["Belief", "Work ethic", "Family lifestyle"],
    group: "Cross-Line",
  },
  {
    name: "Krueger, Derek & Robyn",
    location: "Chicago, IL",
    occupations: "Director of Finance / Project Manager",
    themes: ["Mindset", "Certainty", "Values-based decisions"],
    group: "Cross-Line",
  },
  {
    name: "Kosek, Derek & Jill",
    location: "Chicago, IL",
    occupations: "Pro Soccer & Executive Recruiter / Nanny",
    themes: ["Trusting the system", "Perseverance", "Courage"],
    group: "Cross-Line",
  },
  {
    name: "Holt, Roger & Roxanne",
    location: "Lake Mary, FL",
    occupations: "Army / Human Resources",
    themes: ["Teamwork", "Mentorship", "Serving others"],
    group: "Cross-Line",
  },
  {
    name: "Kopecky, Paul & Morgan",
    location: "Overland Park, KS",
    occupations: "College Athlete / Cosmetologist",
    themes: ["Purpose", "Parenting", "Belief through adversity"],
    group: "Cross-Line",
  },
  {
    name: "Harris, Brent & Brenda",
    location: "Clive, IA",
    occupations: "Police Force / Accounting",
    themes: ["Pace", "Consistency", "Discipline"],
    group: "Cross-Line",
  },
  {
    name: "Gala, Mayank & Sejal",
    location: "Ruckersville, VA",
    occupations: "Students",
    themes: ["Personal development", "Young success", "Urgency"],
    group: "Cross-Line",
  },
  {
    name: "Grotewold, Matt & Alana",
    location: "Blaine, MN",
    occupations: "Construction Worker / Administrative Assistant",
    themes: ["Financial freedom", "Simplicity", "Radical change"],
    group: "Cross-Line",
  },
  {
    name: "Franklin, David & Angie",
    location: "Columbus, OH",
    occupations: "Bank Teller Supervisor / Nurse",
    themes: ["Parenting", "Responsibility", "Self-worth"],
    group: "Cross-Line",
  },
  {
    name: "Francis, Greg & Jacquie",
    location: "East Troy, WI",
    occupations: "Electrical Engineer / Corporate Buyer",
    themes: ["Mentorship", "Early retirement", "Attitude"],
    group: "Cross-Line",
  },
  {
    name: "Elsenpeter, Mark & Anne",
    location: "Minneapolis, MN",
    occupations: "Coach & Teacher / Social Services",
    themes: ["Legacy", "Service", "Intentional leadership"],
    group: "Cross-Line",
  },
  {
    name: "Berendes, Brad & Jodi",
    location: "Omaha, NE",
    occupations: "Teacher & Coach / Bank Teller",
    themes: ["Friendship", "Mentorship", "Imperfect progress"],
    group: "Cross-Line",
  },
  {
    name: "Baker, Jake & Jackie",
    location: "Wake Forest, NC",
    occupations: "Engineer / Chemist",
    themes: ["Generational impact", "Leadership", "Resilience"],
    group: "Cross-Line",
  },
  {
    name: "Ayers, Toby & Mia",
    location: "Heathrow, FL",
    occupations: "Business Executive / Fashion Industry",
    themes: ["Sustained belief", "Excitement", "Leadership"],
    group: "Cross-Line",
  },
  {
    name: "Ayers, Gary & Nancy",
    location: "Lake Mary, FL",
    occupations: "School Teachers",
    themes: ["Faith", "Relationships", "Encouragement"],
    group: "Cross-Line",
  },
  {
    name: "Winston, Manny & Candice",
    location: "Richmond, VA",
    occupations: "Banking / Chemical Management Contractor",
    themes: ["Ambition", "Team culture", "Overcoming average"],
    group: "Cross-Line",
  },
  {
    name: "Wilkins, Devon & Renee",
    location: "Cary, NC",
    occupations: "Tech Sales / Foster Care & Adoption Specialist",
    themes: ["Starting from the bottom", "Ownership", "Values"],
    group: "Cross-Line",
  },
  {
    name: "West, Brandon & Dena",
    location: "Louisville, KY",
    occupations: "Sales / School Teacher",
    themes: ["Hardship", "Focus", "Perseverance"],
    group: "Cross-Line",
  },
  {
    name: "Weir, Doug & Amie",
    location: "Mooresville, NC",
    occupations: "Purchasing Agents",
    themes: ["Helping others", "Family freedom", "Service mindset"],
    group: "Cross-Line",
  },
  {
    name: "Taylor, Terry & Lorri",
    location: "Penn Laird, VA",
    occupations: "Chamber of Commerce Executive / School Teacher",
    themes: ["Long-term leadership", "Courage", "Legacy"],
    group: "Cross-Line",
    note: "Terry passed away in 2017; Lorri and the Taylor Team continue building in his honor.",
  },
  {
    name: "Taylor, Dirk & Laura",
    location: "Harrisonburg, VA",
    occupations: "Manufacturing Supervisor / Ed Tech & Training",
    themes: ["Second-generation LTD", "Earning your way", "Work ethic"],
    group: "Cross-Line",
  },
  {
    name: "Snipes, Danny & Renate",
    location: "Raleigh, NC",
    occupations: "Car Sales Manager / Hotel Supervisor",
    themes: ["Mentorship", "Coaching", "Intentional living"],
    group: "Cross-Line",
  },
  {
    name: "Schwers, Kevin & Amelia",
    location: "Ankeny, IA",
    occupations: "Mechanical Engineer / Exercise Science",
    themes: ["Purpose", "Overcoming challenges", "Change"],
    group: "Cross-Line",
  },
  {
    name: "Pezzimenti, Matthew & Eva",
    location: "Johnson City, TN",
    occupations: "Automotive/Advertising Consultant / Restaurant Owners",
    themes: ["Family time", "Clarity", "Celebration"],
    group: "Cross-Line",
  },
  {
    name: "Newell, Gary & Tammy",
    location: "Kernersville, NC",
    occupations: "Youth Minister / Elementary School Teacher",
    themes: ["Ministry background", "Small consistent steps", "Sacrifice"],
    group: "Cross-Line",
  },
];
