export type Product = {
  name: string;
  brand: string;
  summary: string;
  bestFor: string;
  pv?: string;
};

export const PRODUCTS: Product[] = [
  // Nutrilite
  {
    name: "Double X",
    brand: "Nutrilite",
    summary:
      "Flagship multivitamin/multimineral/phytonutrient system (3 tablets: vitamin, mineral, phytonutrient). Grown on Nutrilite's own farms for full seed-to-supplement traceability.",
    bestFor: "Anyone wanting a foundational daily multivitamin, especially busy professionals and adults 30+.",
    pv: "17.32 PV",
  },
  {
    name: "Nutrilite Double X (10-Day Supply)",
    brand: "Nutrilite",
    summary: "Smaller 10-day trial size of Double X — same formula, shorter supply.",
    bestFor: "First-time Double X customers wanting to try it before committing to a full 31-day supply.",
    pv: "6.30 PV",
  },
  {
    name: "Perfect Pack",
    brand: "Nutrilite",
    summary:
      "Foundational wellness bundle: Double X + Omega-3 + Concentrated Fruits & Vegetables. A complete daily system in one pack.",
    bestFor: "Customers who want comprehensive nutrition without assembling separate products.",
    pv: "43.82 PV",
  },
  {
    name: "Organics Plant Protein",
    brand: "Nutrilite",
    summary: "Plant-based protein (pea, brown rice, chia) — vegan, dairy-free. Supports protein intake, lean muscle, satiety.",
    bestFor: "Vegans, vegetarians, anyone avoiding dairy protein.",
    pv: "10.76 PV",
  },
  {
    name: "Concentrated Fruits & Vegetables",
    brand: "Nutrilite",
    summary: "Concentrated phytonutrients from produce, to fill gaps from low fruit/veg intake. Complements, doesn't replace, a healthy diet.",
    bestFor: "Anyone wanting more antioxidant/phytonutrient support.",
    pv: "12.07 PV",
  },
  {
    name: "Balance Within Probiotic",
    brand: "Nutrilite",
    summary: "Probiotic supporting digestive and immune health via gut microbiome support.",
    bestFor: "Digestive health, immune support.",
    pv: "11.28 PV",
  },
  {
    name: "Prebiotic Fiber",
    brand: "Nutrilite",
    summary: "Fiber supplement supporting digestive health and feeding beneficial gut bacteria.",
    bestFor: "Anyone not getting enough fiber, gut health support alongside a probiotic.",
    pv: "11.02 PV",
  },
  {
    name: "Magnesium",
    brand: "Nutrilite",
    summary: "Supports muscle function, nervous system, relaxation, and energy production.",
    bestFor: "Active adults and anyone with low dietary magnesium intake.",
    pv: "8.92 PV",
  },
  {
    name: "Vitamin D",
    brand: "Nutrilite",
    summary: "Supports bone health, immune function, and muscle function — useful since most people get limited sun exposure.",
    bestFor: "Everyone, especially people with limited outdoor time.",
    pv: "7.61 PV",
  },
  {
    name: "Twist Tubes — Immunity Health",
    brand: "Nutrilite",
    summary: "Strawberry Kiwi single-serving stick pack. Vitamin C + Zinc + antioxidants for immune support.",
    bestFor: "Travelers, teachers, healthcare workers, anyone wanting portable immune support.",
    pv: "6.29 PV",
  },
  {
    name: "Twist Tubes — Antioxidant Health",
    brand: "Nutrilite",
    summary: "Mango Citrus stick pack. Vitamins A & C, antioxidant/cellular protection.",
    bestFor: "Active adults, athletes, health-conscious consumers.",
    pv: "6.29 PV",
  },
  {
    name: "Twist Tubes — Joint Health",
    brand: "Nutrilite",
    summary: "Raspberry stick pack supporting joint flexibility and mobility.",
    bestFor: "Adults 35+, active adults, former athletes.",
    pv: "6.29 PV",
  },
  {
    name: "Begin GI Primer",
    brand: "Nutrilite",
    summary: "Part of the Nutrilite Begin 30 program — supports digestive reset at the start of a wellness routine.",
    bestFor: "Anyone starting the Begin 30 program or wanting a digestive reset.",
    pv: "20.47 PV",
  },
  {
    name: "Nutrilite #nofilter Collagen Peptides",
    brand: "Nutrilite",
    summary: "Collagen peptides supporting skin, hair, nail, and joint health.",
    bestFor: "Anyone wanting collagen support for skin/hair/nails or joints.",
    pv: "8.40 PV",
  },
  {
    name: "CLA",
    brand: "Nutrilite",
    summary: "Conjugated linoleic acid supplement supporting lean body composition alongside diet and exercise.",
    bestFor: "Anyone focused on body composition goals alongside training.",
    pv: "13.64 PV",
  },
  {
    name: "Vitamin C Extended Release",
    brand: "Nutrilite",
    summary: "Extended-release Vitamin C for immune and antioxidant support throughout the day.",
    bestFor: "Anyone wanting all-day Vitamin C support instead of a single spike.",
    pv: "14.17 PV",
  },
  {
    name: "Vitamin C Extended Release (Small)",
    brand: "Nutrilite",
    summary: "Smaller-count size of the same extended-release Vitamin C.",
    bestFor: "Anyone wanting to try it before committing to the larger size.",
    pv: "5.25 PV",
  },
  {
    name: "Prostate Health",
    brand: "Nutrilite",
    summary: "Supplement supporting prostate health for men.",
    bestFor: "Men, especially 40+, wanting proactive prostate support.",
    pv: "12.07 PV",
  },
  {
    name: "Cholesterol Health",
    brand: "Nutrilite",
    summary: "Supplement supporting cholesterol levels already within a normal range.",
    bestFor: "Adults wanting proactive heart-health support.",
    pv: "9.18 PV",
  },
  {
    name: "Omega",
    brand: "Nutrilite",
    summary: "Omega-3 fish oil supporting heart, brain, and joint health.",
    bestFor: "Anyone not eating much fatty fish, heart/brain health focus.",
    pv: "6.30 PV",
  },
  {
    name: "Nutrilite Heart Health CoQ10",
    brand: "Nutrilite",
    summary: "CoQ10 supplement supporting heart health and cellular energy production.",
    bestFor: "Adults wanting heart-health and energy support, especially 40+.",
    pv: "5.25 PV",
  },
  {
    name: "Joint Health",
    brand: "Nutrilite",
    summary: "Supplement supporting joint flexibility and comfort.",
    bestFor: "Active adults, former athletes, anyone with joint stiffness.",
    pv: "16.74 PV",
  },
  {
    name: "Hair, Skin & Nails",
    brand: "Nutrilite",
    summary: "Supplement supporting hair, skin, and nail health.",
    bestFor: "Anyone wanting beauty-from-within support.",
    pv: "6.82 PV",
  },
  {
    name: "Nutrilite Organics Men's Daily Multi Gummies",
    brand: "Nutrilite",
    summary: "Gummy multivitamin formulated for men's daily nutrition needs.",
    bestFor: "Men who prefer a gummy over swallowing tablets.",
    pv: "9.45 PV",
  },
  {
    name: "Nutrilite Liver Support",
    brand: "Nutrilite",
    summary: "Supplement supporting healthy liver function.",
    bestFor: "Adults wanting proactive liver-health support.",
    pv: "9.18 PV",
  },
  {
    name: "Nutrilite Stress Relief Probiotic",
    brand: "Nutrilite",
    summary: "Probiotic formulated to support the gut-brain connection and stress response.",
    bestFor: "Anyone dealing with everyday stress who wants gut-brain support.",
    pv: "12.59 PV",
  },
  {
    name: "Nutrilite Memory Builder",
    brand: "Nutrilite",
    summary: "Supplement supporting memory and cognitive function.",
    bestFor: "Adults wanting proactive brain-health support.",
    pv: "11.02 PV",
  },
  {
    name: "Nutrilite Organics All-in-One Shake (Chocolate)",
    brand: "Nutrilite",
    summary: "Plant-based all-in-one meal replacement shake with protein, fiber, vitamins, and minerals.",
    bestFor: "Anyone wanting a quick, complete meal replacement.",
    pv: "18.89 PV",
  },
  {
    name: "Nutrilite Organics All-in-One Shake (Vanilla)",
    brand: "Nutrilite",
    summary: "Plant-based all-in-one meal replacement shake with protein, fiber, vitamins, and minerals.",
    bestFor: "Anyone wanting a quick, complete meal replacement.",
    pv: "18.89 PV",
  },
  {
    name: "Nutrilite Wellness Bars — Nutty Dark Chocolate",
    brand: "Nutrilite",
    summary: "Snack bar with protein and fiber for an on-the-go wellness snack.",
    bestFor: "Anyone wanting a healthier grab-and-go snack.",
    pv: "7.61 PV",
  },
  {
    name: "Nutrilite Cycle Support",
    brand: "Nutrilite",
    summary: "Supplement supporting women's menstrual cycle health.",
    bestFor: "Women wanting support through their monthly cycle.",
    pv: "9.97 PV",
  },
  {
    name: "Nutrilite Cal Mag D",
    brand: "Nutrilite",
    summary: "Calcium, magnesium, and Vitamin D supplement supporting bone health.",
    bestFor: "Anyone wanting foundational bone-health support.",
    pv: "11.28 PV",
  },
  {
    name: "Nutrilite Vitamin B Dual-Action (120 Tablets)",
    brand: "Nutrilite",
    summary: "B-vitamin complex supporting energy production and nervous system health.",
    bestFor: "Anyone wanting daily energy/metabolism support, larger supply.",
    pv: "9.97 PV",
  },
  {
    name: "Nutrilite Vitamin B Dual-Action (30 Tablets)",
    brand: "Nutrilite",
    summary: "Same B-vitamin complex as the 120-tablet size, in a smaller supply.",
    bestFor: "Anyone wanting to try it before committing to the larger size.",
    pv: "3.35 PV",
  },
  {
    name: "Nutrilite Immunity Defense Zinc + Holy Basil",
    brand: "Nutrilite",
    summary: "Zinc and Holy Basil (Tulsi) blend supporting immune defense.",
    bestFor: "Anyone wanting extra immune support during cold/flu season.",
    pv: "4.66 PV",
  },
  {
    name: "Nutrilite Bone Health Pack",
    brand: "Nutrilite",
    summary: "Bundled pack of bone-health-focused Nutrilite supplements.",
    bestFor: "Adults, especially 50+, wanting a complete bone-health routine.",
    pv: "27.03 PV",
  },
  {
    name: "Nutrilite Kids Daily Chewable Multivitamins",
    brand: "Nutrilite",
    summary: "Chewable multivitamin formulated for kids.",
    bestFor: "Parents wanting a daily multivitamin for their kids.",
    pv: "4.98 PV",
  },
  {
    name: "Nutrilite Complete Menopause Support",
    brand: "Nutrilite",
    summary: "Supplement blend supporting women through menopause.",
    bestFor: "Women navigating menopause symptoms.",
    pv: "10.23 PV",
  },
  {
    name: "Nutrilite Iron Folic",
    brand: "Nutrilite",
    summary: "Iron and folic acid supplement supporting healthy red blood cell production.",
    bestFor: "Anyone with low dietary iron intake, women of childbearing age.",
    pv: "4.46 PV",
  },
  {
    name: "Nutrilite Organics All-in-One Meal Powder (Chocolate)",
    brand: "Nutrilite",
    summary: "Plant-based all-in-one meal replacement powder with protein, fiber, vitamins, and minerals.",
    bestFor: "Anyone wanting a quick, complete meal replacement.",
    pv: "18.36 PV",
  },
  {
    name: "Nutrilite Organics All-in-One Meal Powder (Vanilla)",
    brand: "Nutrilite",
    summary: "Plant-based all-in-one meal replacement powder with protein, fiber, vitamins, and minerals.",
    bestFor: "Anyone wanting a quick, complete meal replacement.",
    pv: "18.36 PV",
  },
  {
    name: "Nutrilite Organics Turmeric Capsules",
    brand: "Nutrilite",
    summary: "Turmeric/curcumin capsules supporting joint comfort and healthy inflammation response.",
    bestFor: "Anyone wanting joint or everyday inflammation support.",
    pv: "8.66 PV",
  },
  {
    name: "Nutrilite Organics Turmeric Gummies",
    brand: "Nutrilite",
    summary: "Gummy version of the same turmeric/curcumin support.",
    bestFor: "Anyone who prefers a gummy over capsules.",
    pv: "10.50 PV",
  },
  {
    name: "Nutrilite Organics Ashwagandha Capsules",
    brand: "Nutrilite",
    summary: "Ashwagandha capsules supporting stress response and everyday resilience.",
    bestFor: "Anyone wanting adaptogen support for everyday stress.",
    pv: "11.55 PV",
  },
  // XS
  {
    name: "XS Energy Drink",
    brand: "XS",
    summary:
      "Sugar-free energy drink, ~114mg caffeine, B vitamins, 15 calories. Many flavors (Classic, Citrus, Tropical, Root Beer, Black Cherry Cola, and more); CF Cranberry-Grape is caffeine-free.",
    bestFor: "Anyone wanting a lower-sugar energy drink alternative.",
    pv: "~9.70 PV (variety case)",
  },
  {
    name: "XS Pre-Workout Boost",
    brand: "XS",
    summary: "Green Apple or Blue Raspberry. Energy, focus, and endurance support for training.",
    bestFor: "Gym-goers, strength training, HIIT.",
  },
  {
    name: "XS Post-Workout Recovery",
    brand: "XS",
    summary: "Fruit Punch. L-Glutamine, amino acids, turmeric, glucosamine for muscle recovery and joint support.",
    bestFor: "Anyone training regularly who wants to recover faster.",
    pv: "8.66 PV",
  },
  {
    name: "XS Grass-Fed Whey Protein",
    brand: "XS",
    summary: "30g whey protein isolate, 6.9g BCAAs, gluten/soy free, stevia-sweetened. Chocolate, Vanilla, Strawberry.",
    bestFor: "Active adults increasing protein intake; not for those avoiding dairy.",
    pv: "16.01 PV",
  },
  {
    name: "XS Muscle Multiplier",
    brand: "XS",
    summary: "Essential amino acid + L-Arginine blend, zero sugar, caffeine-free. Supports lean muscle, strength, recovery.",
    bestFor: "Anyone wanting amino acid support before/during/after training.",
    pv: "13.11 PV",
  },
  {
    name: "XS Creatine+",
    brand: "XS",
    summary: "5g Creatine Monohydrate + Calcium HMB + electrolyte matrix for strength, power, and hydration.",
    bestFor: "Strength training, gym performance.",
    pv: "14.43 PV",
  },
  {
    name: "XS Sports Twist Tubes",
    brand: "XS",
    summary: "Fruit Punch or Raspberry Lemonade. Hydration and electrolyte replenishment, portable stick packs.",
    bestFor: "Athletes, golfers, runners, anyone trying to drink more water.",
    pv: "6.03 PV",
  },
  {
    name: "XS Sports Protein Bar",
    brand: "XS",
    summary: "Protein bar for on-the-go recovery or a protein-forward snack.",
    bestFor: "Athletes and gym-goers wanting a portable protein snack.",
    pv: "11.02 PV",
  },
  {
    name: "XS CocoWater",
    brand: "XS",
    summary: "Coconut water-based hydration mix for electrolyte replenishment.",
    bestFor: "Anyone wanting a natural-leaning hydration option.",
    pv: "7.35 PV",
  },
  // Artistry
  {
    name: "Artistry Skin Nutrition (Balancing / Hydrating / Renewing)",
    brand: "Artistry",
    summary:
      "Premium skincare line built on White Chia Seed + Acerola Cherry. Balancing = combination/oily skin. Hydrating = dry/mature skin. Renewing = fine lines/firmness/dullness (35+).",
    bestFor: "Matching by skin concern: oiliness, dryness, or anti-aging.",
  },
  {
    name: "Artistry Makeup (Foundation, Concealer, Powder, etc.)",
    brand: "Artistry",
    summary: "Foundation, concealer, powder, blush, bronzer, highlighter, eye/lip products — formulated to support skin comfort while enhancing appearance.",
    bestFor: "Customers wanting makeup with skincare benefits.",
  },
  {
    name: "Artistry Signature Select",
    brand: "Artistry",
    summary: "Customizable mask system: Hydration, Brightening, Purifying, Firming, Polishing.",
    bestFor: "Customers wanting a personalized treatment routine.",
  },
  {
    name: "Artistry Vitamin C + HA3 Daily Serum",
    brand: "Artistry",
    summary: "Brightening serum with Vitamin C and hyaluronic acid for daily use.",
    bestFor: "Anyone wanting a brightening, hydrating daily serum.",
    pv: "15.21 PV",
  },
  {
    name: "Artistry Renewing Reactivation Crème",
    brand: "Artistry",
    summary: "Anti-aging cream from the Renewing line, focused on firmness and fine lines.",
    bestFor: "Adults 35+ wanting an anti-aging daily moisturizer.",
    pv: "19.21 PV",
  },
  // Satinique
  {
    name: "Satinique Smooth Moisture Shampoo (Regular)",
    brand: "Satinique",
    summary: "Shampoo for dry, frizzy, or coarse hair. Enerjuve technology (lipids, creatine, 18-MEA) for shine and manageability.",
    bestFor: "\"My hair is dry/frizzy/hard to manage.\"",
    pv: "3.94 PV",
  },
  {
    name: "Satinique Smooth Moisture Shampoo (Large)",
    brand: "Satinique",
    summary: "Larger-size bottle of the same Smooth Moisture Shampoo.",
    bestFor: "Households wanting to stock up and maximize PV per order.",
    pv: "7.35 PV",
  },
  {
    name: "Satinique Smooth Moisture Conditioner (Regular)",
    brand: "Satinique",
    summary: "Conditioner pairing with Smooth Moisture Shampoo for dry, frizzy, or coarse hair.",
    bestFor: "\"My hair is dry/frizzy/hard to manage.\"",
    pv: "3.94 PV",
  },
  {
    name: "Satinique Smooth Moisture Conditioner (Large)",
    brand: "Satinique",
    summary: "Larger-size bottle of the same Smooth Moisture Conditioner.",
    bestFor: "Households wanting to stock up and maximize PV per order.",
    pv: "7.35 PV",
  },
  {
    name: "Satinique Intensive Repair Shampoo (Regular)",
    brand: "Satinique",
    summary: "Shampoo for damaged, color-treated, or heat-styled hair — reduces breakage and improves texture over time.",
    bestFor: "People who color, flat-iron, or frequently blow-dry.",
    pv: "4.20 PV",
  },
  {
    name: "Satinique Intensive Repair Shampoo (Large)",
    brand: "Satinique",
    summary: "Larger-size bottle of the same Intensive Repair Shampoo.",
    bestFor: "Households wanting to stock up and maximize PV per order.",
    pv: "7.61 PV",
  },
  {
    name: "Satinique Intensive Repair Conditioner (Large)",
    brand: "Satinique",
    summary: "Conditioner pairing with Intensive Repair Shampoo for damaged, color-treated, or heat-styled hair.",
    bestFor: "People who color, flat-iron, or frequently blow-dry.",
    pv: "7.61 PV",
  },
  {
    name: "Satinique Intensive Repair Hair Lotion",
    brand: "Satinique",
    summary: "Leave-in treatment lotion for damaged hair, part of the Intensive Repair line.",
    bestFor: "People who color, flat-iron, or frequently blow-dry.",
    pv: "5.77 PV",
  },
  {
    name: "Satinique Intensive Repair Hair Oil Serum",
    brand: "Satinique",
    summary: "Finishing oil serum for shine and frizz control, part of the Intensive Repair line.",
    bestFor: "People who color, flat-iron, or frequently blow-dry.",
    pv: "7.61 PV",
  },
  {
    name: "Satinique Purifying Scalp & Hair Shampoo (Regular)",
    brand: "Satinique",
    summary: "Shampoo focused on scalp health and a deeper, purifying cleanse.",
    bestFor: "Anyone wanting a clarifying, scalp-focused shampoo.",
    pv: "3.94 PV",
  },
  {
    name: "Satinique Purifying Scalp & Hair Shampoo (Large)",
    brand: "Satinique",
    summary: "Larger-size bottle of the same Purifying Scalp & Hair Shampoo.",
    bestFor: "Households wanting to stock up and maximize PV per order.",
    pv: "7.35 PV",
  },
  {
    name: "Satinique Purifying Scalp & Hair Conditioner (Regular)",
    brand: "Satinique",
    summary: "Conditioner pairing with Purifying Scalp & Hair Shampoo.",
    bestFor: "Anyone wanting a clarifying, scalp-focused hair care routine.",
    pv: "3.94 PV",
  },
  {
    name: "Satinique Anti-Dandruff Scalp & Hair Shampoo (Regular)",
    brand: "Satinique",
    summary: "Shampoo formulated to help control dandruff and support scalp health.",
    bestFor: "Anyone dealing with dandruff or an itchy, flaky scalp.",
    pv: "3.94 PV",
  },
  {
    name: "Satinique Anti-Dandruff Scalp & Hair Shampoo (Large)",
    brand: "Satinique",
    summary: "Larger-size bottle of the same Anti-Dandruff Shampoo.",
    bestFor: "Households wanting to stock up and maximize PV per order.",
    pv: "7.35 PV",
  },
  {
    name: "Satinique Anti-Hair Fall Scalp & Hair Conditioner (Large)",
    brand: "Satinique",
    summary: "Conditioner formulated to support scalp health and reduce hair fall from breakage.",
    bestFor: "Anyone concerned about hair fall or thinning-feeling hair.",
    pv: "7.61 PV",
  },
  {
    name: "Satinique Color Care",
    brand: "Satinique",
    summary: "Gentle, color-safe cleansing that helps maintain vibrancy for color-treated hair.",
    bestFor: "Color-treated or highlighted hair.",
  },
  // G&H
  {
    name: "G&H Protect Hand Soap",
    brand: "G&H",
    summary: "Gentle hand soap built around White Tea Extract, focused on cleansing while protecting the skin's moisture barrier.",
    bestFor: "Families, anyone with dry skin who wants gentle daily cleansing.",
    pv: "2.49 PV",
  },
  {
    name: "G&H Protect Bar Soap",
    brand: "G&H",
    summary: "Bar soap version of the G&H Protect line — same gentle, moisture-barrier-friendly cleansing.",
    bestFor: "Families, anyone with dry skin who wants gentle daily cleansing.",
    pv: "7.61 PV",
  },
  {
    name: "G&H Nourish Body Wash",
    brand: "G&H",
    summary: "Everyday body wash built around White Tea Extract, focused on cleansing while protecting the skin's moisture barrier.",
    bestFor: "Families, anyone with dry skin who wants gentle daily cleansing.",
    pv: "3.80 PV",
  },
  {
    name: "G&H Nourish Body Wash (Large)",
    brand: "G&H",
    summary: "Larger-size bottle of the same G&H Nourish Body Wash.",
    bestFor: "Households wanting to stock up and maximize PV per order.",
    pv: "7.61 PV",
  },
  {
    name: "G&H Nourish Body Lotion",
    brand: "G&H",
    summary: "Daily moisturizing lotion, same White Tea Extract-based line.",
    bestFor: "Anyone wanting daily moisturizing paired with the body wash/soap.",
    pv: "4.13 PV",
  },
  {
    name: "G&H Protect Antiperspirant Deodorant Roll-On",
    brand: "G&H",
    summary: "Roll-on antiperspirant/deodorant.",
    bestFor: "Everyday antiperspirant/deodorant use.",
    pv: "2.82 PV",
  },
  {
    name: "G&H Protect Aluminum Free Deodorant",
    brand: "G&H",
    summary: "Aluminum-free deodorant option for those avoiding antiperspirants.",
    bestFor: "Anyone preferring an aluminum-free deodorant.",
    pv: "3.28 PV",
  },
  {
    name: "G&H Protect Body Lotion SPF 50",
    brand: "G&H",
    summary: "Daily body lotion with SPF 50 sun protection.",
    bestFor: "Anyone wanting daily moisturizing with sun protection built in.",
    pv: "7.35 PV",
  },
  {
    name: "G&H Dynamic Duo",
    brand: "G&H",
    summary: "6-product starter bundle covering the core G&H Protect/Nourish lineup at a bundled price.",
    bestFor: "First-time G&H customers wanting to try the line without buying each piece separately.",
    pv: "7.87 PV",
  },
  {
    name: "G&H Refresh Exfoliating Body Wash",
    brand: "G&H",
    summary: "Exfoliating body wash from the G&H Refresh line.",
    bestFor: "Anyone wanting a gentle exfoliating cleanse.",
    pv: "3.80 PV",
  },
  {
    name: "G&H Refresh Exfoliating Body Wash (Large)",
    brand: "G&H",
    summary: "Larger-size bottle of the same G&H Refresh Exfoliating Body Wash.",
    bestFor: "Households wanting to stock up and maximize PV per order.",
    pv: "7.61 PV",
  },
  {
    name: "G&H Refresh Body Milk",
    brand: "G&H",
    summary: "Lightweight daily moisturizer from the G&H Refresh line.",
    bestFor: "Anyone wanting a lighter, everyday moisturizer.",
    pv: "4.13 PV",
  },
  {
    name: "G&H Baby Wash & Shampoo",
    brand: "G&H",
    summary: "Gentle 2-in-1 wash and shampoo formulated for babies.",
    bestFor: "New parents, baby showers, families with young kids.",
    pv: "4.07 PV",
  },
  {
    name: "G&H Baby Lotion",
    brand: "G&H",
    summary: "Gentle daily moisturizer formulated for babies.",
    bestFor: "New parents, baby showers, families with young kids.",
    pv: "4.07 PV",
  },
  // Glister
  {
    name: "Glister Multi-Action Toothpaste",
    brand: "Glister",
    summary: "Fluoride + Reminact remineralization technology + silica polishing agents. Plaque removal, cavity prevention, fresh breath, stain removal.",
    bestFor: "Daily oral care, families.",
    pv: "2.03 PV",
  },
  {
    name: "Glister Travel Size Multi-Action Toothpaste, 6-pack",
    brand: "Glister",
    summary: "Same formula as the full-size toothpaste, in travel-friendly tubes.",
    bestFor: "Travelers, gym bags, kids' backpacks, sampling for new customers.",
    pv: "5.51 PV",
  },
  {
    name: "Glister Multi-Action Concentrated Oral Rinse",
    brand: "Glister",
    summary: "Concentrated mouthwash — complements brushing/flossing for a complete daily oral care routine.",
    bestFor: "Anyone wanting a full oral care system.",
    pv: "3.67 PV",
  },
  {
    name: "Glister Mint Refresher Spray",
    brand: "Glister",
    summary: "Portable breath-freshening spray for on-the-go touch-ups between brushing.",
    bestFor: "On-the-go breath freshening.",
    pv: "1.90 PV",
  },
  {
    name: "Glister Multi-Action Power Toothbrush",
    brand: "Glister",
    summary: "Rechargeable sonic toothbrush with multiple cleaning modes.",
    bestFor: "Anyone wanting an upgrade from a manual toothbrush.",
    pv: "45.92 PV",
  },
  {
    name: "Glister Multi-Action Power Toothbrush Refills",
    brand: "Glister",
    summary: "Replacement brush heads for the Glister power toothbrush.",
    bestFor: "Power toothbrush owners due for a refill.",
    pv: "9.45 PV",
  },
  // Home / durables
  {
    name: "eSpring Water Treatment System",
    brand: "Home",
    summary: "Carbon block filtration + UV technology. Reduces lead, chlorine, sediment, and microorganisms while retaining beneficial minerals. Not reverse osmosis.",
    bestFor: "Families and health-conscious homeowners concerned about water quality.",
  },
  {
    name: "Atmosphere Sky Air Treatment",
    brand: "Home",
    summary: "3-stage filtration: pre-filter, HEPA-grade, carbon (odors/VOCs).",
    bestFor: "Allergy sufferers, pet owners, families.",
    pv: "448.69 PV",
  },
  {
    name: "iCook 4-Piece Stock Pot",
    brand: "Home",
    summary: "4 L/4 quart stainless stock pot with steamer/colander insert. Multi-ply construction for even heating; waterless-cooking philosophy for flavor/nutrient retention.",
    bestFor: "Home cooks wanting durable, premium cookware.",
    pv: "83.70 PV",
  },
  {
    name: "iCook 5-Piece Sauté Set",
    brand: "Home",
    summary: "Stainless sauté pans with lids. Multi-ply construction for even heating; waterless-cooking philosophy for flavor/nutrient retention.",
    bestFor: "Home cooks wanting durable, premium cookware.",
    pv: "123.06 PV",
  },
  {
    name: "iCook 5-Piece Knifeware Set",
    brand: "Home",
    summary: "Kitchen knife set covering everyday prep and cutting tasks.",
    bestFor: "Home cooks wanting a durable, premium knife set.",
    pv: "136.19 PV",
  },
  {
    name: "LOC Multi-Purpose Cleaner",
    brand: "Amway Home",
    summary: "Concentrated cleaner for countertops, floors, appliances, and more — one product replacing several.",
    bestFor: "Anyone wanting to simplify their cleaning cabinet.",
    pv: "3.28 PV",
  },
  {
    name: "LOC Multi-Purpose Wipes",
    brand: "Amway Home",
    summary: "Pre-moistened version of LOC — for quick cleanups without mixing a spray bottle.",
    bestFor: "Grab-and-go cleaning, quick countertop wipe-downs.",
    pv: "4.00 PV",
  },
  {
    name: "Amway Home Glass Cleaner",
    brand: "Amway Home",
    summary: "Streak-free cleaner for windows, mirrors, and other glossy surfaces.",
    bestFor: "Anyone wanting a streak-free clean for windows and mirrors.",
    pv: "4.46 PV",
  },
  {
    name: "Dish Drops",
    brand: "Amway Home",
    summary: "Concentrated, grease-cutting dishwashing liquid.",
    bestFor: "Everyday dishwashing.",
  },
  {
    name: "SA8 Laundry Detergent + Stain Remover + Fabric Softener",
    brand: "Amway Home",
    summary: "Concentrated laundry system: cleaning power, fabric care, HE-compatible (verify current label).",
    bestFor: "Everyday laundry.",
  },
];

export type PVReference = { item: string; pv: string };

export const PV_REFERENCE: PVReference[] = [
  { item: "Nutrilite Twist Tubes (any flavor)", pv: "6.29 PV" },
  { item: "XS Sports Twist Tubes", pv: "6.03 PV" },
  { item: "XS CocoWater Hydration Mix", pv: "7.35 PV" },
  { item: "XS Energy Variety Case", pv: "9.70 PV" },
  { item: "XS Protein Crisps", pv: "10.23 PV" },
  { item: "XS Protein Bars", pv: "11.02 PV" },
  { item: "Artistry Go Lipstick", pv: "6.82 PV" },
  { item: "Artistry Ever Perfect Foundation", pv: "11.28 PV" },
  { item: "Artistry Signature Select Hydrating Mask", pv: "11.02 PV" },
  { item: "XS Sports Protein Shakes", pv: "13.91 PV" },
  { item: "XS Creatine+ / XS Muscle Multiplier", pv: "14.43 PV" },
  { item: "XS Grass-Fed Whey / XS CBD Cream", pv: "16.01 PV" },
  { item: "Artistry Renewing Reactivation Day Lotion SPF 30", pv: "19.41 PV" },
  { item: "Artistry Labs Retexturizing Serum", pv: "28.86 PV" },
  { item: "Artistry Renewing System Bundle", pv: "37.77 PV" },
  { item: "Artistry LongXevity Soft Cream", pv: "95.77 PV" },
];

export type StarterStack = {
  name: string;
  detail: string;
  bestFor: string;
};

export const STARTER_STACKS: StarterStack[] = [
  { name: "Beauty Starter Stack", detail: "7 products, ~53.71 PV", bestFor: "Beauty/skincare customers, self-care routines" },
  { name: "Customer Faves Starter Stack", detail: "8 products, ~53.72 PV", bestFor: "First-time customers, families, people unsure where to start" },
  { name: "Nutrition Starter Stack", detail: "6 products, ~54.66 PV", bestFor: "Nutrition-focused, wellness-minded households" },
  { name: "Sports Nutrition Starter Stack", detail: "8 products, ~73.19 PV", bestFor: "Athletes, gym-goers, recovery-focused" },
  { name: "The Essentials Stack", detail: "10 products, 56.30 PV", bestFor: "New IBOs building consistent monthly consumption" },
  { name: "Fitness Jump Start Solution", detail: "Item #128210, ~46.44 PV", bestFor: "Weight loss goals, new fitness journeys, beginners" },
  { name: "Muscle Gains Stack", detail: "7 products, ~77.27 PV", bestFor: "Muscle growth, bulking phases" },
  { name: "Toning Stack", detail: "~7 products", bestFor: "Lean muscle, fat loss, body recomposition" },
  { name: "Peak Performance Stack", detail: "5 products, ~53.98 PV", bestFor: "Competitive athletes, advanced training" },
  { name: "Healthy Aging Solution", detail: "37.52 PV", bestFor: "Adults wanting a comprehensive daily anti-aging/wellness routine" },
  { name: "Everyday Nutrition Solution (Unflavored or Chocolate)", detail: "38.58 PV", bestFor: "Households wanting a complete daily nutrition system" },
  { name: "Inner + Outer Beauty Solution", detail: "85.01 PV", bestFor: "Customers wanting both skincare and beauty-from-within nutrition" },
  { name: "Walking to Bronze Bundle", detail: "57.47 PV", bestFor: "New IBOs building toward their first rank advancement" },
  { name: "Energy Solution", detail: "40.14 PV", bestFor: "Anyone wanting a complete daily energy-support system" },
  { name: "Nutrilite Begin 30 Holistic Wellness Program Solution", detail: "53.27 PV", bestFor: "New team members starting the Begin 30 program" },
  { name: "Hydrating Skin Care Solution", detail: "43.54 PV", bestFor: "Customers wanting a complete hydrating skincare routine" },
];
